// auto generated by go tool dist
// goos=windows goarch=amd64

#include "runtime.h"
void
runtime·GOMAXPROCS(int32 n, uint32, int32 ret)
{
#line 939 "C:\Users\ADMINI~1\AppData\Local\Temp\2\bindist269497170\go\src\pkg\runtime\runtime1.goc"

	ret = runtime·gomaxprocsfunc(n);
	FLUSH(&ret);
}
void
runtime·NumCPU(int32 ret)
{
#line 943 "C:\Users\ADMINI~1\AppData\Local\Temp\2\bindist269497170\go\src\pkg\runtime\runtime1.goc"

	ret = runtime·ncpu;
	FLUSH(&ret);
}
